# format version 3.3 is compatible with docker engine 17.06.0+
version: "3.3"

services:
  mariadb:
    build: mariadb
    container_name: mariadb
    restart: always
    volumes: ["/Users/anduuin/data/mariadb:/var/lib/mysql"]
    networks: 
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: wordpress
    container_name: wordpress
    restart: always
    volumes: ["/Users/anduuin/data/wordpress:/srv/www"]
    networks: 
      - backend
      - frontend
    environment:
      DB_USER: ${MYSQL_USER}
      DB_NAME: ${MYSQL_DATABASE}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE} 
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

  redis:
    build: redis
    container_name: redis
    restart: always
    networks:
      - backend

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    volumes: ["/Users/anduuin/data/wordpress:/srv/www"]
    networks: ["frontend"]
    ports: ["443:443"]
    environment:
      SERVER_NAME: ${WP_URL}

  sftp:
    build: sftp
    container_name: sftp
    restart: always
    volumes: ["/Users/anduuin/data/wordpress:/srv/www"]
    ports: ["4242:22"]
    environment:
      SFTP_PASSWORD: ${SFTP_PASSWORD}

  mkdocs:
    build: mkdocs
    container_name: mkdocs
    restart: always
    networks:
      - frontend
    environment:
      SITE_URL: ${WP_URL}

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
