# format version 3.3 is compatible with docker engine 17.09.0+
version: "3.3"

services:
  db:
    build: "./mariadb"
    volumes: ["./mariadb/data:/var/lib/mysql"]
    networks: ["db-wordpress"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: "./wordpress"
    volumes: ["./wordpress/data:/srv/www"]
    depends_on: ["db"]
    networks: 
      - db-wordpress
      - wordpress-nginx
    environment:
      DB_USER: ${MYSQL_USER}
      DB_NAME: ${MYSQL_DATABASE}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY} 
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}


  nginx:
    build: "./nginx"
    volumes: ["./wordpress/data:/srv/www"]
    depends_on: ["wordpress"]
    networks: ["wordpress-nginx"]
    ports: ["80:80"]

networks:
  db-wordpress:
    driver: bridge
  wordpress-nginx:
    driver: bridge
