# format version 3.3 is compatible with docker engine 17.09.0+
version: "3.3"

services:
  mariadb:
    build: "./mariadb"
    volumes: ["/home/cjeon/data/mariadb:/var/lib/mysql"]
    networks: ["mariadb-wordpress"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: "./wordpress"
    volumes: ["/home/cjeon/data/wordpress:/srv/www"]
    depends_on: ["mariadb"]
    networks: 
      - mariadb-wordpress
      - wordpress-nginx
    environment:
      DB_USER: ${MYSQL_USER}
      DB_NAME: ${MYSQL_DATABASE}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE} 
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

  nginx:
    build: "./nginx"
    volumes: ["/home/cjeon/data/wordpress:/srv/www"]
    depends_on: ["wordpress"]
    networks: ["wordpress-nginx"]
    ports: ["443:443"]

networks:
  mariadb-wordpress:
    driver: bridge
  wordpress-nginx:
    driver: bridge
