# format version 3.4 is compatible with docker engine 17.09.0+
version: "3.3"

services:
  db:
    build: "./mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  wordpress:
    build: "./wordpress"
    